/*
 * SpinnerDialog.java
 *
 * Created on __DATE__, __TIME__
 */
package edu.uci.grad.security.gui;

import edu.uci.grad.security.SystemwideConstants;

/**
 *
 * @author __USER__
 */
public class SpinnerDialog extends javax.swing.JDialog {

    /**
     * Creates new form SpinnerDialog
     */
    public SpinnerDialog(java.awt.Frame parent, boolean modal) {
	super(parent, modal);
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pleaseWaitLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setIconImage((new javax.swing.ImageIcon(getClass().getResource("/images/dbpmLogo.png"))).getImage());
        setModalityType(ModalityType.MODELESS);
        setName("spinnerDialog"); // NOI18N

        pleaseWaitLabel.setText("Please wait while " + edu.uci.grad.security.SystemwideConstants.PROJECT_NAME + " loads.");

        jProgressBar1.setIndeterminate(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pleaseWaitLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pleaseWaitLabel)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //
    //	/**
    //	 * @param args the command line arguments
    //	 */
    //	public static void main(String args[]) {
    //		java.awt.EventQueue.invokeLater(new Runnable() {
    //			public void run() {
    //				SpinnerDialog dialog = new SpinnerDialog(
    //						new javax.swing.JFrame(), true);
    //				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    //					public void windowClosing(java.awt.event.WindowEvent e) {
    //						System.exit(0);
    //					}
    //				});
    //				dialog.setVisible(true);
    //			}
    //		});
    //	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel pleaseWaitLabel;
    // End of variables declaration//GEN-END:variables
}